### ISSUE TITLE
Retroavtivly join all public channels in slack

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/professor-bloom#4]

**Comment by cskartikey** [comment]
Why is this required? Isn't it limited to just welcome?

**Comment by jaspermayone** [comment]
See second part of use case message in slack, 
![CleanShot 2024-04-10 at 12 02 51@2x](https://github.com/hackclub/professor-bloom/assets/65788728/ba85df00-e212-4087-a91b-e6c63f98e85b)

**Comment by jaspermayone** [comment]
Sorry totally forgot to send that message in my drafts.

**Comment by jaspermayone** [comment]
This is blocked until I meet with graham on chronicle
