### ISSUE TITLE
Create easy buttons / welcome ui for new user

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/professor-bloom#6]

**Comment by cskartikey** [comment]
Is this for the people being welcomed or the welcomers responding?

**Comment by jaspermayone** [comment]
This is for the welcomers to respond. Design idea similar to CRT flow

![CleanShot 2024-04-09 at 22 20 28@2x](https://github.com/hackclub/professor-bloom/assets/65788728/17907090-8773-49c8-8e68-fa930e146a19)

**Comment by jaspermayone** [comment]
the idea would be for the welcomer to push a button, and get a modal pre-filled with their default template for them to edit. Then they would click the submit button on the model, and the initial message would be sent from their account, to the user. (we implemented the permissions here)
